"""Observation Model

Revision ID: 06600f194fb3
Revises: bc494540d50e
Create Date: 2020-01-11 16:33:33.237128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06600f194fb3'
down_revision = 'bc494540d50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation')
    # ### end Alembic commands ###
